<div class="col-md-12">
<div class="col-md-6">
<center><button type="button" class="btn default" onclick="exportTableToExcel('printTable', 'Transport Fee Structure')"><i class="fa fa-print" aria-hidden="true"></i>Print In Excel</button></center>
</div>
<div class="col-md-6">
<center><button type="button" class="btn default" onclick="for_print();"><i class="fa fa-print" aria-hidden="true"></i>Print In Pdf</button></center>
</div>
</div>

        <div class="col-md-12">
          <!-- /.box -->
          <div class="box">
            <!-- /.box-header -->
			<div class="col-md-10 col-md-offset-1">
            <div class="box-body table-responsive" id="printTable">
						<table cellspacing="0" cellpadding="5px;" class="" style="width:100%">
			<tr>
			<td colspan="3"><span style="font-size:20px;font-weight:bold"><center><b>SIMPTION TECH PVT LTD</b></center></span></td>
			</tr>
			<tr>
			<td style="float:left"><b>Dise Code : 23260100164</b></td>
			<td><center><b>STUDENT TRANSPORT STRUCTURE</b></center></td>
			<td style="float:right"><b>School Code : 50702</b></td>
			</tr>
			<tr>
			<td colspan="3"><center><b>Classwise</b></center></td>
			</tr>
			</table>
				  
				  <table id="example1" class="table table-bordered table-striped" border="1px" cellpadding="10px" cellspacing="0" width="100%">
					<thead class="my_background_color">
					<tr>
					  <td>S.No.</td>
					  <td>Root Name</td>
					  					  <td>NURSERY</td>
					  					  <td>LKG</td>
					  					  <td>UKG</td>
					  					  <td>1ST</td>
					  					  <td>2ND</td>
					  					  <td>3RD</td>
					  					  <td>4TH</td>
					  					  <td>5TH</td>
					  					  <td>6TH</td>
					  					  <td>7TH</td>
					  					  <td>8TH</td>
					  					  <td>9TH</td>
					  					  <td>10TH</td>
					  					  <td>11TH</td>
					  					  <td>12TH</td>
					  					</tr>
					</thead>
					<tbody>
										 <tr>
					 <td>1</td>
					 <td>NASRULLAGANJ</td>
					 					 <td>4800</td>
					 					 <td>6600</td>
					 					 <td>1600</td>
					 					 <td>1600</td>
					 					 <td>1600</td>
					 					 <td>1600</td>
					 					 <td>1600</td>
					 					 <td>1600</td>
					 					 <td>1600</td>
					 					 <td>1600</td>
					 					 <td>1600</td>
					 					 <td>1600</td>
					 					 <td>1600</td>
					 					 <td>1600</td>
					 					 <td>1600</td>
					 					</tr>
										 <tr>
					 <td>2</td>
					 <td>RALA</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					</tr>
										 <tr>
					 <td>3</td>
					 <td>BORKHEDA</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					 <td>1800</td>
					 					</tr>
										 <tr>
					 <td>4</td>
					 <td>MP</td>
					 					 <td>600</td>
					 					 <td>600</td>
					 					 <td>600</td>
					 					 <td>600</td>
					 					 <td>600</td>
					 					 <td>600</td>
					 					 <td>600</td>
					 					 <td>600</td>
					 					 <td>600</td>
					 					 <td>600</td>
					 					 <td>600</td>
					 					 <td>600</td>
					 					 <td>600</td>
					 					 <td>600</td>
					 					 <td>600</td>
					 					</tr>
										 <tr>
					 <td>5</td>
					 <td>subhas nagar</td>
					 					 <td>501</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					</tr>
										 <tr>
					 <td>6</td>
					 <td>20000</td>
					 					 <td>3000</td>
					 					 <td>3000</td>
					 					 <td>3000</td>
					 					 <td>3000</td>
					 					 <td>3000</td>
					 					 <td>3000</td>
					 					 <td>3000</td>
					 					 <td>3000</td>
					 					 <td>3000</td>
					 					 <td>3000</td>
					 					 <td>3000</td>
					 					 <td>3000</td>
					 					 <td>3000</td>
					 					 <td>3000</td>
					 					 <td>3000</td>
					 					</tr>
										 <tr>
					 <td>7</td>
					 <td>mp nagar</td>
					 					 <td>2200</td>
					 					 <td>2200</td>
					 					 <td>2200</td>
					 					 <td>2200</td>
					 					 <td>2200</td>
					 					 <td>2200</td>
					 					 <td>2200</td>
					 					 <td>2200</td>
					 					 <td>2200</td>
					 					 <td>2200</td>
					 					 <td>2200</td>
					 					 <td>2200</td>
					 					 <td>2200</td>
					 					 <td>2200</td>
					 					 <td>2200</td>
					 					</tr>
										 <tr>
					 <td>8</td>
					 <td>ashoka garden</td>
					 					 <td>2500</td>
					 					 <td>2500</td>
					 					 <td>2500</td>
					 					 <td>2500</td>
					 					 <td>2500</td>
					 					 <td>2500</td>
					 					 <td>2500</td>
					 					 <td>2500</td>
					 					 <td>2500</td>
					 					 <td>2500</td>
					 					 <td>2500</td>
					 					 <td>2500</td>
					 					 <td>2500</td>
					 					 <td>2500</td>
					 					 <td>2500</td>
					 					</tr>
										 <tr>
					 <td>9</td>
					 <td>kolar</td>
					 					 <td>1000</td>
					 					 <td>1000</td>
					 					 <td>1000</td>
					 					 <td>1000</td>
					 					 <td>1000</td>
					 					 <td>1000</td>
					 					 <td>1000</td>
					 					 <td>1000</td>
					 					 <td>1000</td>
					 					 <td>1000</td>
					 					 <td>1000</td>
					 					 <td>1000</td>
					 					 <td>1000</td>
					 					 <td>1000</td>
					 					 <td>1000</td>
					 					</tr>
										 <tr>
					 <td>10</td>
					 <td>bardi</td>
					 					 <td>4000</td>
					 					 <td>4000</td>
					 					 <td>4000</td>
					 					 <td>4000</td>
					 					 <td>4000</td>
					 					 <td>4000</td>
					 					 <td>4000</td>
					 					 <td>4000</td>
					 					 <td>4000</td>
					 					 <td>4000</td>
					 					 <td>4000</td>
					 					 <td>4000</td>
					 					 <td>4000</td>
					 					 <td>4000</td>
					 					 <td>4000</td>
					 					</tr>
										 <tr>
					 <td>11</td>
					 <td>mp.nagar</td>
					 					 <td>4400</td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					</tr>
										 <tr>
					 <td>12</td>
					 <td>arwind vihar</td>
					 					 <td>5000</td>
					 					 <td>5000</td>
					 					 <td>5000</td>
					 					 <td>5000</td>
					 					 <td>5000</td>
					 					 <td>5000</td>
					 					 <td>5000</td>
					 					 <td>5000</td>
					 					 <td>5000</td>
					 					 <td>5000</td>
					 					 <td>5000</td>
					 					 <td>5000</td>
					 					 <td>5000</td>
					 					 <td>5000</td>
					 					 <td>5000</td>
					 					</tr>
										 <tr>
					 <td>13</td>
					 <td>kalpna nagar</td>
					 					 <td>3500</td>
					 					 <td>3500</td>
					 					 <td>3500</td>
					 					 <td>3500</td>
					 					 <td>3500</td>
					 					 <td>3500</td>
					 					 <td>3500</td>
					 					 <td>3500</td>
					 					 <td>3500</td>
					 					 <td>3500</td>
					 					 <td>3500</td>
					 					 <td>3500</td>
					 					 <td>3500</td>
					 					 <td>3500</td>
					 					 <td>3500</td>
					 					</tr>
										 <tr>
					 <td>14</td>
					 <td>KHANDAKPAR</td>
					 					 <td>5220</td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					</tr>
										 <tr>
					 <td>15</td>
					 <td>Bhel </td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					 <td>2000</td>
					 					</tr>
										 <tr>
					 <td>16</td>
					 <td>MOD</td>
					 					 <td>2000</td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					</tr>
										 <tr>
					 <td>17</td>
					 <td>mp nagar</td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					</tr>
										 <tr>
					 <td>18</td>
					 <td>mp nagar</td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					</tr>
										 <tr>
					 <td>19</td>
					 <td>mp nagar </td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					 <td></td>
					 					</tr>
										</tbody>
				 </table>
			  
        <!-- /.col -->
      </div>
      </div>
			  <div class="col-md-12">&nbsp;</div>
			  <div class="col-md-12">
			  <div class="col-md-6">
			  <center><button type="button" class="btn my_background_color" onclick="exportTableToExcel('printTable', 'Transport Fee Structure')"><i class="fa fa-print" aria-hidden="true"></i>  Print In Excel</button></center>
			  </div>
			  <div class="col-md-6">
			  <center><button type="button" class="btn my_background_color" onclick="for_print();"><i class="fa fa-print" aria-hidden="true"></i>  Print In Pdf</button></center>
			  </div>
			  </div>
  </div>
</div>