<option value="">Select Subject</option>
<option value="Animal Husbandry And Poultary Farm">Animal Husbandry And Poultary Farm</option>
<option value="Cleanliness">Cleanliness</option>
<option value="Computer">Computer</option>
<option value="Drawing / Painting">Drawing / Painting</option>
<option value="English">English</option>
<option value="ENGLISH (SPECIAL)">ENGLISH (SPECIAL)</option>
<option value="EVS">EVS</option>
<option value="Games">Games</option>
<option value="General Knowledge">General Knowledge</option>
<option value="GK & DRAWING">GK & DRAWING</option>
<option value="Hindi ">Hindi </option>
<option value="Homework">Homework</option>
<option value="Kasganj">Kasganj</option>
<option value="Mathematics">Mathematics</option>
<option value="Maths ">Maths </option>
<option value="Music">Music</option>
<option value="ORGANIC CHEMISTRY ">ORGANIC CHEMISTRY </option>
<option value="Other activity">Other activity</option>
<option value="Physics">Physics</option>
<option value="PROJECT WORK (ENGLISH)">PROJECT WORK (ENGLISH)</option>
<option value="Regularity">Regularity</option>
<option value="Sanskrit ">Sanskrit </option>
<option value="Science">Science</option>
<option value="social sciences">social sciences</option>
<option value="sre">sre</option>
<option value="testr">testr</option>
