<option value="Computer">Computer</option>
<option value="English">English</option>
<option value="EVS">EVS</option>
<option value="Drawing / Painting">Drawing / Painting</option>
<option value="Hindi ">Hindi </option>
<option value="Sanskrit ">Sanskrit </option>
<option value="Mathematics">Mathematics</option>
<option value="social sciences">social sciences</option>
<option value="PROJECT WORK (ENGLISH)">PROJECT WORK (ENGLISH)</option>
<option value="Games">Games</option>
<option value="SCIENCE">SCIENCE</option>
<option value="Animal Husbandry And Poultary Farm">Animal Husbandry And Poultary Farm</option>
<option value="General Knowledge">General Knowledge</option>
<option value="ORGANIC CHEMISTRY ">ORGANIC CHEMISTRY </option>
<option value="CHEMISTRY">CHEMISTRY</option>
<option value="AG BIO">AG BIO</option>
